version: '3.8'
services:
  app:
    image: ghcr.io/matthewglenn/remotionworkspace:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: remotionworkspace
    ports:
      - "8083:3000"
    volumes:
      - $PUBLIC:/public
      - $SRC:/src