version: '3.8'
services:
  app:
    image: ghcr.io/matthewglenn/remotionworkspace:latest
    container_name: remotionworkspace
    ports:
      - "8080:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start